"""Appendix tables that no cached block produces.

`pipeline.tables` writes every other table from a cached block; these six run
their own measurement instead (the whole set takes ~40 min), so `api.tables()`
does not call them.

    python -m pipeline.appendix_tables            # all six
    python -m pipeline.appendix_tables floor mesh # a subset

Each file carries a provenance header.
"""
from __future__ import annotations

import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from . import cache, metrics
from .compute import (SEED_TRAIN, SEED_VALID, cross_section, latin_hypercube,
                      solver_for, _xsec)
from .plan_calibration import calibration_for
from .settings import DECLARED
from .systems import SYSTEMS

OUT = Path("tables_out")

SUITE = ("n40Ca", "alpha12C_band", "alpha24Mg", "n238U")
MACRO = {"n40Ca": r"\sysCa{} ", "alpha12C_band": r"\sysC{}  ",
         "alpha24Mg": r"\sysMg{} ", "n238U": r"\sysU{}  "}

SEED_OUTSIDE = 90210          # the widened-box draws, distinct from validation
SEED_EPSTOL = 777             # the 200 draws of the tolerance experiment
EPS_POST = 5e-3


# --- helpers ---

def _header(what, seconds):
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    where = cache.name() or "results"
    return ("% GENERATED by pipeline.appendix_tables -- do not edit.\n"
            f"% cache={where}  measurement={what}  written={stamp}"
            f"  took={seconds:.0f}s\n"
            "% Regenerate with:  python -m pipeline.appendix_tables\n"
            "% This one runs its own measurement; api.tables() does not "
            "produce it.\n")


def _sci(x, digits=1):
    """A number as $a x 10^b$; a non-finite value as a dash."""
    x = float(x)
    if not np.isfinite(x) or x == 0.0:
        return "--" if not np.isfinite(x) else "$0$"
    e = int(np.floor(np.log10(abs(x))))
    return r"$%.*f\times10^{%d}$" % (digits, x / 10.0 ** e, e)


def _sci_floor(x, floor=1e-16, digits=1):
    """As _sci, but anything under the floor prints as a bound.

    The cusp table reaches 1e-42 and 1e-92 on the elements of a channel that
    has just opened. Those exponents are the numerical zero of a ratio whose
    two sides are both zero, not a measurement, and printing them invites the
    reader to take them for one.
    """
    x = float(x)
    if np.isfinite(x) and 0.0 < x < floor:
        return r"$<10^{%d}$" % int(round(np.log10(floor)))
    return _sci(x, digits)


def _write(name, text):
    OUT.mkdir(exist_ok=True)
    path = OUT / f"{name}.tex"
    path.write_text(text, encoding="utf-8")
    print(f"  wrote {path}")
    return path


def _emulators(key, nb=None, K=None):
    """A trained RBM and LROM at the calibrated configuration of `key`."""
    from core.rbm import RBMEmulator
    from core.lrom_dbmm import LROMEmulator

    system = SYSTEMS[key]
    channels, model, theta_c, bounds = system.preset_fn()
    E = float(system.E_demo)
    cal = calibration_for(key)
    th_train = latin_hypercube(cal.Ns, bounds, seed=SEED_TRAIN)
    base = solver_for(system, theta_c, energies=[E])

    rbm = RBMEmulator(base, E)
    rbm.fit(model, th_train, eps_tol=1e-14, nb_max=nb or cal.nb)
    lrom = LROMEmulator(base, E)
    lrom.fit(model, th_train, theta_c,
             K_diag=cal.K_diag if K is None else K, K_coup=cal.K_coup,
             eps_tol=1e-14, nb_max=nb or cal.nb)
    return system, model, theta_c, bounds, E, cal, base, rbm, lrom


# --- 1. the two solvers, element by element ---

def table_solver_floor():
    r"""Median and p95 of the DBMM against the R-matrix code, per element group.

    The project's metric convention throughout: per (theta, E) pair the reading
    is the WORST relative difference over the diagonal elements, and the worst
    over the off-diagonal elements that exist; the median and percentile are
    then taken over the pairs.
    """
    t0 = time.perf_counter()
    rows = []
    for key in ("alpha12C_band", "alpha24Mg", "n238U"):
        d, _ = cache.read(key, "validation")
        A, B = np.asarray(d["S_dbmm"]), np.asarray(d["S_rmat"])
        n = A.shape[-1]
        eye = np.eye(n, dtype=bool)
        rel = np.abs(A - B) / np.maximum(np.abs(B), 1e-300)
        big = np.max(np.abs(B), axis=tuple(range(B.ndim - 2)))
        off = (big > 1e-8 * big.max()) & ~eye

        P = np.sqrt(np.abs(A * np.swapaxes(A, -1, -2)))
        Q = np.sqrt(np.abs(B * np.swapaxes(B, -1, -2)))
        geo = np.abs(P - Q) / np.maximum(np.abs(Q), 1e-300)

        def ms(x):
            x = np.asarray(x, dtype=float).ravel()
            x = x[np.isfinite(x)]
            return (np.median(x), np.percentile(x, 95)) if x.size else (np.nan,) * 2

        v = (ms(np.max(rel[..., eye], axis=-1))
             + ms(np.max(rel[..., off], axis=-1))
             + ms(np.max(geo[..., off], axis=-1)))
        rows.append("%s & %s & %s & %s & %s\n         & %s & %s \\\\"
                    % ((MACRO[key],) + tuple(_sci(x) for x in v)))

    body = "\n".join(rows)
    text = _header("DBMM against the R-matrix code, from the validation block",
                   time.perf_counter() - t0) + r"""
\begin{table}[H]
\centering
\caption[The two solvers element by element]{The two solvers element by element, median and $95$th
percentile of the relative difference over $40$ parameters and $60$ energies. Each reading is the
worst element of its group at one parameter and one energy, the convention of
Table~\ref{tab:metrics}; the median and the percentile are then taken over the $2400$ pairs. The
last column is the geometric mean of a reciprocal pair, and it is optimistic against the elements
themselves on all three systems.}
\label{tab:solver_floor}
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
& \multicolumn{2}{c}{diagonal} & \multicolumn{2}{c}{off-diagonal}
& \multicolumn{2}{c}{$\sqrt{|U_{\alpha\beta}U_{\beta\alpha}|}$} \\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}
System & median & p95 & median & p95 & median & p95 \\
\midrule
""" + body + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    return _write("t_solver_floor", text)


# --- 2. alpha+24Mg against a fine mesh ---

def table_mg_mesh(ladder=(100, 140, 180, 240), fine=320):
    """Both codes at four mesh sizes, each against its own finest mesh."""
    from core import python_rmatrix as rmat

    t0 = time.perf_counter()
    key = "alpha24Mg"
    system = SYSTEMS[key]
    channels, model, theta_c, _ = system.preset_fn()
    E, R = float(system.E_demo), system.R

    def dbmm_at(N):
        return solver_for(system, theta_c, energies=[E], N=N).solve(E)

    def rmat_at(N):
        mesh, _ = rmat.compute_lagrange_mesh(N, R)
        lag_b = rmat.eval_lag_at_boundary(mesh, R)
        Bm = rmat.make_boundary_matrix(mesh, R, channels, E)
        V_diag, V_coup = model(theta_c)
        if V_coup is None:
            def V_coup(r, ca, cb):
                return np.zeros_like(r, dtype=complex)
        H = rmat.compute_CC_ham(mesh, R, channels, V_diag, V_coup)
        S, _ = rmat.compute_S_matrix(H + Bm, lag_b, channels, E, R, mesh,
                                     compute_wfs=False)
        return S

    def rel(X, Y):
        return float(np.max(np.abs(X - Y) / np.maximum(np.abs(Y), 1e-300)))

    D = {N: dbmm_at(N) for N in ladder + (fine,)}
    Rm = {N: rmat_at(N) for N in ladder + (fine,)}
    rows = ["$%d$ & %s & %s & %s \\\\"
            % (N, _sci(rel(D[N], D[fine])), _sci(rel(Rm[N], Rm[fine])),
               _sci(rel(D[N], Rm[N]))) for N in ladder]

    Ns = np.array(ladder, dtype=float)
    order = {n: np.polyfit(np.log(Ns),
                           np.log([rel(dd[int(N)], dd[fine]) for N in Ns]), 1)[0]
             for n, dd in (("dbmm", D), ("rmat", Rm))}
    const = rel(D[ladder[0]], D[fine]) / rel(Rm[ladder[0]], Rm[fine])

    text = _header("alpha+24Mg, both codes against N=%d" % fine,
                   time.perf_counter() - t0) + (
        "%% DBMM falls as N^%.1f, R-matrix as N^%.1f, constant ratio %.0f\n"
        % (order["dbmm"], order["rmat"], const)) + r"""
\begin{table}[H]
\centering
\caption[The two solvers against a refined mesh]{The two solvers against a refined mesh, on
$\alpha+{}^{24}$Mg at its central parameters and its demonstration energy, worst relative difference
over the elements of $\mathbf{U}$. Each code is measured against its own answer at $N=320$, so the
first two columns are convergence and the third is the disagreement between implementations. The
gap between column one and column three at the working mesh is how far the \dbmm{} is from
converged.}
\label{tab:mg_mesh}
\begin{tabular}{@{}rrrr@{}}
\toprule
$N$ & \dbmm{} against $N=320$ & R-matrix against $N=320$ & code against code \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    return _write("t_mg_mesh", text)


# --- 3. the truncation tolerance ---

def table_epstol(tols=(1e-8, 1e-6, 1e-5), n_valid=200):
    """Rank, error and online time at three truncation tolerances.

    The error is the one on U as a whole, which is the quantity the
    Eckart-Young bound applies to and therefore the one the sqrt(eps) estimate
    is compared against.
    """
    from core.rbm import RBMEmulator

    t0 = time.perf_counter()
    rows = []
    for i, key in enumerate(SUITE):
        system = SYSTEMS[key]
        channels, model, theta_c, bounds = system.preset_fn()
        E = float(system.E_demo)
        cal = calibration_for(key)
        dim = len(channels) * system.N
        th_train = latin_hypercube(cal.Ns, bounds, seed=SEED_TRAIN)
        th_valid = latin_hypercube(n_valid, bounds, seed=SEED_EPSTOL)
        base = solver_for(system, theta_c, energies=[E])
        S_ref = np.array([solver_for(system, t, energies=[E]).solve(E)
                          for t in th_valid])

        emu = RBMEmulator(base, E)
        emu.fit(model, th_train, eps_tol=1e-14)
        X_full, K_full = emu.X_r, emu.K
        sv = emu.singular_values
        disc = 1.0 - np.cumsum(sv ** 2) / np.sum(sv ** 2)

        if i:
            rows.append(r"\addlinespace[2pt]")
        for j, tol in enumerate(tols):
            nb = (int(np.argmax(disc < tol)) + 1) if (disc < tol).any() \
                else int(X_full.shape[1])
            nb = min(nb, X_full.shape[1])
            emu.X_r = X_full[:, :nb]
            emu.K_r = emu.X_r.conj().T @ K_full @ emu.X_r
            S = np.array([emu.predict(t) for t in th_valid])
            err = np.asarray(metrics.err_global(S, S_ref), dtype=float)
            err = err[np.isfinite(err)]
            ms = min(_timed(lambda t=th_valid[k]: emu.predict(t))
                     for k in range(5))
            head = MACRO[key] if j == 0 else " " * len(MACRO[key])
            rows.append("%s & $10^{%d}$ & $%d$ & $%.0f\\%%$ & %s & %s & $%.2f$ \\\\"
                        % (head, int(round(np.log10(tol))), nb,
                           100 * nb / dim, _sci(np.median(err)),
                           _sci(np.percentile(err, 95)), ms))
        emu.X_r, emu.K_r = X_full, X_full.conj().T @ K_full @ X_full

    text = _header("truncation tolerance, %d validation draws" % n_valid,
                   time.perf_counter() - t0) + r"""
\begin{table}[H]
\centering
\caption[Measured effect of a looser truncation tolerance]{Measured effect of a looser truncation
tolerance. Rank, rank fraction, median and $95$th percentile of the relative error on $\mathbf{U}$,
which is the quantity the Eckart-Young bound applies to, and online time, over $200$ validation
parameters. The rank is read at the demonstration energy, whereas the calibration takes the maximum
over the energy window, which is why these ranks differ by a few from Table~\ref{tab:manifold}. The
operating target is $\epsilon_{\rm post}=5\times10^{-3}$; entries above it are configurations that no
longer clear it at the median.}
\label{tab:epstol}
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
System & $\epsilon_{\rm tol}$ & $n_b$ & $n_b/N_cN$ & median error & p95 error & online (ms) \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    return _write("t_epstol", text)


def _timed(fn, n=25):
    best = np.inf
    for _ in range(n):
        t0 = time.perf_counter()
        fn()
        best = min(best, time.perf_counter() - t0)
    return best * 1e3


# --- 4. conditioning of the reduced solve ---

def table_conditioning(n_valid=30):
    """cond(M_r) at every rank of the calibrated ladder, beside the error there.

    The error column is read from the manifold block, not measured again, so the
    table and its figure cannot disagree about where a system floors. The
    best-approximation column is the distance from a validation solution the
    basis never saw to the subspace, at the same ranks: it says whether a floor
    belongs to the subspace or to the projected solve.
    """
    from core.rbm import (RBMEmulator, project_potential,
                          eval_potential_on_mesh)

    t0 = time.perf_counter()
    rows = []
    for i, key in enumerate(SUITE):
        system = SYSTEMS[key]
        channels, model, theta_c, bounds = system.preset_fn()
        E = float(system.E_demo)
        cal = calibration_for(key)
        th_train = latin_hypercube(cal.Ns, bounds, seed=SEED_TRAIN)
        th_valid = latin_hypercube(n_valid, bounds, seed=SEED_VALID)
        base = solver_for(system, theta_c, energies=[E])

        emu = RBMEmulator(base, E)
        emu.fit(model, th_train, eps_tol=1e-14)
        X_full, K_full = emu.X_r, emu.K
        # The out-of-sample solutions themselves, solved once and projected at
        # every rank below. Columns are (theta, entrance channel).
        C_valid = emu.snapshots(model, th_valid)
        nrm_valid = np.linalg.norm(C_valid, axis=0)

        d, _ = cache.read(key, "manifold")
        nb_scan = np.asarray(d["nb_scan"]).ravel()
        eg = np.asarray(d["err_global"], dtype=float)
        med = (np.nanmedian(eg, axis=tuple(range(1, eg.ndim)))
               if eg.ndim > 1 else eg)

        if i:
            rows.append(r"\addlinespace[2pt]")
        for j, nb in enumerate(nb_scan):
            nb = int(nb)
            if nb > X_full.shape[1]:
                continue
            emu.X_r = X_full[:, :nb]
            emu.K_r = emu.X_r.conj().T @ K_full @ emu.X_r
            conds = []
            for t in th_valid:
                Vn, Vc = eval_potential_on_mesh(emu._model, t, emu.base)
                V_r = project_potential(emu.X_r, Vn, Vc, emu.N, emu.Nc)
                conds.append(np.linalg.cond(emu.K_r + V_r))
            proj = C_valid - emu.X_r @ (emu.X_r.conj().T @ C_valid)
            best = float(np.median(np.linalg.norm(proj, axis=0) / nrm_valid))
            head = MACRO[key] if j == 0 else " " * len(MACRO[key])
            rows.append("%s & $%d$ & $%.0f$ & $%.0f$ & %s & %s \\\\"
                        % (head, nb, np.median(conds), np.max(conds),
                           _sci(best), _sci(med[j])))
        emu.X_r, emu.K_r = X_full, X_full.conj().T @ K_full @ X_full

    text = _header("conditioning over the calibrated ladder",
                   time.perf_counter() - t0) + r"""
\begin{table}[H]
\centering
\caption[Conditioning of the reduced solve against rank]{Conditioning of the reduced solve against
rank, median and worst over $30$ validation draws, beside the distance from an unseen solution to
the subspace and the median error on $\mathbf{U}$, all at the same rank. The rank ladder is the
calibrated one of Appendix~\ref{app:calibration}. The best-approximation column is
$\lVert\mathbf{c}-X_rX_r^{H}\mathbf{c}\rVert/\lVert\mathbf{c}\rVert$ at the validation draws, so
it is what the subspace can do before any equation is projected onto it, where the column beside
it is what the projected solve does instead. \sysCa{} and \sysU{} are the two systems whose error
stops falling.}
\label{tab:conditioning}
\begin{tabular}{@{}lrrrrr@{}}
\toprule
System & $n_b$ & median $\mathrm{cond}$ & worst $\mathrm{cond}$ & best approximation & median error \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    return _write("t_conditioning", text)


# --- 5. outside the training box ---

def table_outside(widths=(1.0, 1.2, 1.5), n_valid=40):
    """Error at three box widths, emulators trained on the nominal one.

    Measured on sigma, because the tolerance the table is read against is
    stated on sigma.
    """
    t0 = time.perf_counter()

    def widen(bounds, f):
        lo, hi = bounds[:, 0], bounds[:, 1]
        c, h = 0.5 * (lo + hi), 0.5 * (hi - lo) * f
        return np.stack([c - h, c + h], axis=1)

    rows = []
    for i, key in enumerate(SUITE):
        (system, model, theta_c, bounds, E, cal, base,
         rbm, lrom) = _emulators(key)
        kind = _xsec(system, DECLARED[key])
        if i:
            rows.append(r"\addlinespace[2pt]")
        for j, f in enumerate(widths):
            th = latin_hypercube(n_valid, widen(bounds, f), seed=SEED_OUTSIDE)
            S_ref = np.array([solver_for(system, t, energies=[E]).solve(E)
                              for t in th])
            sig_ref = np.array([cross_section(base, E, S, kind) for S in S_ref])
            out = []
            for emu in (rbm, lrom):
                S = np.array([emu.predict(t) for t in th])
                sig = np.array([cross_section(base, E, s1, kind) for s1 in S])
                e = np.asarray(metrics.err_observable(sig, sig_ref), dtype=float)
                e = e[np.isfinite(e)]
                out += [np.median(e), np.percentile(e, 95)]
            head = MACRO[key] if j == 0 else " " * len(MACRO[key])
            rows.append("%s & $%.1f$ & %s & %s & %s & %s \\\\"
                        % ((head, f) + tuple(_sci(x) for x in out)))

    text = _header("outside the training box, %d draws per width" % n_valid,
                   time.perf_counter() - t0) + r"""
\begin{table}[H]
\centering
\caption[Error outside the training box]{Error outside the training box. The emulators are those
trained on the nominal box; only the sampling box is widened, by the factor in column two. Median
and $95$th percentile of the relative error on $\sigma$ at the demonstration energy, over $40$ draws
none of which is in any training set.}
\label{tab:outside}
\begin{tabular}{@{}lrrrrr@{}}
\toprule
& & \multicolumn{2}{c}{\rbm{}} & \multicolumn{2}{c}{\lrom{}} \\
\cmidrule(lr){3-4}\cmidrule(lr){5-6}
System & width & median & p95 & median & p95 \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    return _write("t_outside", text)


# --- 6. close to a channel threshold ---

def table_cusp(offsets=(0.010, 0.050, 0.200), n_valid=30):
    """Error at three offsets above each threshold of alpha+12C.

    The left pair is the median over the elements of U that exist, not the
    worst of them: on this system the off-diagonal elements span five decades
    within one draw, so a worst-case reading is carried by the smallest.
    """
    from core.rbm import RBMEmulator
    from core.lrom_dbmm import LROMEmulator

    t0 = time.perf_counter()
    key = "alpha12C_band"
    system = SYSTEMS[key]
    channels, model, theta_c, bounds = system.preset_fn()
    cal = calibration_for(key)
    th_train = latin_hypercube(cal.Ns, bounds, seed=SEED_TRAIN)
    th_valid = latin_hypercube(n_valid, bounds, seed=SEED_VALID)
    thr = np.array([c.get("threshold", 0.0) for c in channels])
    e2, e4 = sorted(set(float(t) for t in thr if t > 0))[:2]

    plan = [("demonstration", float(system.E_demo)), (None, None)]
    for lab, eps in ((r"\epsilon_2", e2), (r"\epsilon_4", e4)):
        for off in offsets:
            plan.append((r"$%s+%d$ keV" % (lab, round(off * 1000)), eps + off))
        if lab == r"\epsilon_2":
            plan.append((None, None))

    def med_all(S, S_ref, mask):
        rel = np.abs(S - S_ref) / np.maximum(np.abs(S_ref), 1e-300)
        keep = mask | np.eye(mask.shape[0], dtype=bool)
        v = rel[:, keep]
        v = v[np.isfinite(v)]
        return float(np.median(v)) if v.size else np.nan

    rows = []
    for label, E in plan:
        if label is None:
            rows.append(r"\addlinespace[2pt]")
            continue
        base = solver_for(system, theta_c, energies=[E])
        S_ref = np.array([solver_for(system, t, energies=[E]).solve(E)
                          for t in th_valid])
        mask = metrics.coupling_mask(S_ref)
        rbm = RBMEmulator(base, E)
        rbm.fit(model, th_train, eps_tol=1e-14, nb_max=cal.nb)
        lrom = LROMEmulator(base, E)
        lrom.fit(model, th_train, theta_c, K_diag=cal.K_diag,
                 K_coup=cal.K_coup, eps_tol=1e-14, nb_max=cal.nb)
        v = []
        for emu in (rbm, lrom):
            S = np.array([emu.predict(t) for t in th_valid])
            v.append((med_all(S, S_ref, mask),
                      float(np.nanmedian(np.asarray(
                          metrics.err_elastic(S, S_ref), dtype=float)))))
        rows.append("%-20s & $%.3f$ & $%d$ & %s & %s\n"
                    "                     & %s & %s \\\\"
                    % (label, E, int(np.sum(thr < E)),
                       _sci_floor(v[0][0]), _sci_floor(v[1][0]),
                       _sci(v[0][1]), _sci(v[1][1])))

    text = _header("alpha+12C close to each threshold",
                   time.perf_counter() - t0) + r"""
\begin{table}[H]
\centering
\caption[Emulator error close to a channel threshold]{Emulator error close to a channel threshold,
on \sysC, median over $30$ validation draws. The two left columns are the median over the elements
of $\mathbf{U}$ that exist; the two right columns are the elastic element alone. Within tens of keV
of a threshold the first metric collapses, and that collapse is the physics rather than a fault: the
channels that have just opened carry almost no flux, so solver and emulator return the same
numerical zero for them and a relative error on those elements means nothing, so anything under
$10^{-16}$ is printed as a bound. The elastic element is
of order unity at every energy and is what can be compared across the table.}
\label{tab:cusp}
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
& & & \multicolumn{2}{c}{all elements} & \multicolumn{2}{c}{elastic element} \\
\cmidrule(lr){4-5}\cmidrule(lr){6-7}
Energy & $E$ (MeV) & open & \rbm{} & \lrom{} & \rbm{} & \lrom{} \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    return _write("t_cusp", text)


# --- driver ---

ALL = {"floor": table_solver_floor, "mesh": table_mg_mesh,
       "epstol": table_epstol, "cond": table_conditioning,
       "outside": table_outside, "cusp": table_cusp}


def write_all(only=None):
    names = list(ALL) if not only else [n for n in only if n in ALL]
    t0 = time.perf_counter()
    for name in names:
        print(f"[{name}]", flush=True)
        ALL[name]()
    print("done in %.0f s" % (time.perf_counter() - t0))


if __name__ == "__main__":
    write_all(sys.argv[1:] or None)
