"""The document's tables, generated from the cache instead of typed.

Every table here is built from `pipeline.views`, not from the cache directly: a
view is what a figure draws, so a table from the same call cannot disagree with
the figure beside it. Where a view did not already expose the summary a table
needs, the summary was added to the view, never recomputed here.

    from pipeline import api
    api.tables()                      # write tables_out/*.tex, show what changed

Every file carries a header naming the cache, the date and the block it came
from.
"""
import re
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

from . import cache, metrics, views
from .plan_calibration import calibration_for
from .settings import SUITE
from .systems import SYSTEMS

OUT = Path("tables_out")


def out_dir():
    """Where tables go for the cache in force, mirroring draw.out_dir()."""
    return OUT if not cache.name() else OUT / cache.name()


# --- formatting -------------------------------------------------------

def _sci(x, digits=1):
    """1.6e-04 as $1.6\\times10^{-4}$, and a missing value as a dash."""
    x = float(x)
    if not np.isfinite(x):
        return "--"
    if x == 0.0:
        return "$0$"
    exp = int(np.floor(np.log10(abs(x))))
    mant = x / 10.0 ** exp
    return rf"${mant:.{digits}f}\times10^{{{exp}}}$"


def _num(x, digits=2):
    return "--" if not np.isfinite(float(x)) else f"${float(x):.{digits}f}$"


def _gain(x):
    """A gain: no decimal past ten, one below it, a dash if missing. Formatted
    here so the rule cannot drift between two tables."""
    x = float(x)
    if not np.isfinite(x):
        return "--"
    return rf"$\times{x:.0f}$" if x >= 10 else rf"$\times{x:.1f}$"


def _header(block, extra=""):
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    where = cache.name() or "results"
    return ("% GENERATED by pipeline.tables -- do not edit.\n"
            f"% cache={where}  block={block}  written={stamp}\n"
            f"% Regenerate with:  api.tables()\n"
            + (f"% {extra}\n" if extra else ""))


def _short(caption, limit=92, floor=30):
    """The list-of-tables entry: the caption's first sentence, cut back at a
    clause boundary if it is longer than a line."""
    head = re.split(r"(?<=[a-z0-9)])\.\s", caption.strip(), maxsplit=1)[0]
    head = re.sub(r"\s+", " ", head).rstrip(".")
    plain = re.sub(r"\\[a-zA-Z]+\{[^{}]*\}", "xxx", head)
    plain = re.sub(r"[\\{}$]", "", plain)
    if len(plain) <= limit:
        return head
    best = None
    for m in re.finditer(r"(?<=[a-z0-9)]),\s|:\s|;\s", head):
        cut = head[:m.start()].rstrip(" ,;:")
        n = len(re.sub(r"[\\{}$]", "", re.sub(r"\\[a-zA-Z]+\{[^{}]*\}", "xxx", cut)))
        if floor <= n <= limit and (best is None or n > best[1]):
            best = (cut, n)
    return best[0] if best else head


def _tabular(header_rows, body_rows, spec, caption, label, block, note="",
             compact=False):
    """One table environment. `compact` (tabcolsep 2pt) is for a table too wide
    for the text block; the body size is set by main.tex, so it is not touched
    here.
    """
    lines = [_header(block, note),
             r"\begin{table}[H]", r"\centering",
             rf"\caption[{_short(caption)}]{{{caption}}}", rf"\label{{{label}}}"]
    if compact:
        lines += [r"\setlength{\tabcolsep}{2pt}"]
    lines += [rf"\begin{{tabular}}{{@{{}}{spec}@{{}}}}", r"\toprule"]
    lines += header_rows
    lines.append(r"\midrule")
    lines += body_rows
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


# --- the tables ------------------------------------------------------

def table_manifold(systems=SUITE):
    """Rank, its share of the ambient dimension, and what each method achieves.

    Columns 5-7 are `observable_vs_emulators` medians over every validation draw
    and energy node; column 4 is the error at the top rung of the rank ladder.
    """
    rows, eps = [], None
    n_demo, n_draw, n_node = None, None, None
    for key in systems:
        system = SYSTEMS[key]
        d, meta = cache.read(key, "manifold")
        # from the block's metadata, not a live probe: the quoted rank must be
        # the one the numbers beside it were computed at.
        nb = int(meta.get("nb") or calibration_for(key).nb)
        eps = meta.get("eps_sol", eps)
        dim = system.n_channels * system.N
        err_sigma = np.asarray(d["err_sigma"], dtype=float)
        top = float(np.nanmedian(err_sigma[-1])) if err_sigma.size else np.nan
        notes = views.observable_vs_emulators(key)["error"].notes
        # columns 5 and 6-7 are the same method at the same rank, differing only
        # in what they average over (the caption says which).
        n_demo = err_sigma.shape[1] if err_sigma.ndim == 2 else n_demo
        d_exc, _ = cache.read(key, "excitation")
        err_exc = np.asarray(d_exc["err_rbm"])
        if err_exc.ndim == 2:
            n_draw, n_node = err_exc.shape
        rows.append(rf"{system.label} & ${dim}$ & ${nb}$ & "
                    rf"${100.0 * nb / dim:.0f}\%$ & {_sci(top)} & "
                    rf"{_sci(notes.get('median_rbm', np.nan))} & "
                    rf"{_sci(notes.get('median_lrom', np.nan))} \\")

    caption = (
        rf"The manifold, and what the emulators achieve on it. The rank is the "
        rf"one the truncation criterion selects at "
        # the document's symbol (\epsilon_{\rm tol}), not the code's variable
        # name (eps_sol).
        rf"$\epsilon_{{\rm tol}}={_sci(eps, 0)[1:-1]}$, and the three error "
        rf"columns are all quoted at it. Column~5 is obtained at the "
        rf"demonstration energy alone, over ${n_demo}$ validation parameters; "
        rf"columns~6 and~7 over ${n_draw}$ validation parameters and all "
        rf"${n_node}$ energies of the window.")
    return _tabular(
        [r"& & \multicolumn{2}{c}{retained rank} "
         r"& \multicolumn{3}{c}{median relative error on $\sigma$, at that rank}\\",
         r"\cmidrule(lr){3-4}\cmidrule(lr){5-7}",
         r"& & & & at $E_{\rm demo}$ "
         r"& \multicolumn{2}{c}{over the energy window}\\",
         r"\cmidrule(lr){5-5}\cmidrule(lr){6-7}",
         r"System & $N_cN$ & retained rank $n_b$ & $n_b/N_cN$ & RBM & RBM & LROM \\"],
        rows, "lrrrrrr", caption, "tab:manifold", "manifold + excitation")


def operating_rows(system_key):
    """The operating configuration of each method, with its cost and its error.

    Shared with `table_cost` and `macros()` so a sentence never names a
    configuration the table beside it does not. The operating point is
    `metrics.operating_point` (cheapest configuration clearing the tolerance),
    never chosen by eye.

    Returns (solver_costs, [per-method dict]). The error is measured on the
    quantity the cost-accuracy sheets use -- off-diagonal where one exists,
    diagonal otherwise.
    """
    d, meta = cache.read(system_key, "cat")
    # from the block, not a live probe: the training size the block used.
    n_train = int(meta.get("n_train") or calibration_for(system_key).Ns)

    method = np.asarray(d["method"]).astype(str)
    nb = np.asarray(d["nb_kept"], dtype=float)
    kd = np.asarray(d["K_diag"], dtype=float)
    kc = np.asarray(d["K_coup"], dtype=float)
    t_on = np.asarray(d["t_online"], dtype=float) * 1e3
    quantity = ("err_Sab" if np.isfinite(np.asarray(d["err_Sab"])).any()
                else "err_S00")
    err = np.asarray(d[quantity], dtype=float)

    solver = dict(
        n_train=n_train, quantity=quantity,
        # the p95 columns are read off this many draws (a tail statistic without
        # its sample size is not a measurement).
        n_valid=int(meta.get("n_valid") or 0),
        t_rmat=float(np.median(np.asarray(d["t_rmat"], dtype=float))) * 1e3,
        t_full=float(np.median(np.asarray(d["t_dbmm_full"], dtype=float))) * 1e3,
        t_V=float(np.median(np.asarray(d["t_dbmm_V"], dtype=float))) * 1e3)

    out = []
    for m, tag in (("rbm", "RBM"), ("lrom", "LROM")):
        combos, seen = [], set()
        for i in range(method.size):
            sig = (method[i], nb[i], kd[i], kc[i])
            if method[i] == m and sig not in seen:
                seen.add(sig)
                combos.append(sig)
        if not combos:
            continue
        costs, errs, labels = [], [], []
        for (_, b, a, c) in combos:
            sel = (method == m) & (nb == b) & (kd == a) & (kc == c)
            costs.append(float(np.median(t_on[sel])))
            errs.append(float(np.nanmedian(err[sel])))
            labels.append(rf"$n_b\,{b:.0f}$" if m == "rbm"
                          else (rf"$K\,{a:.0f}{{+}}{c:.0f}$" if c
                                else rf"$K\,{a:.0f}$"))
        i = metrics.operating_point(errs, costs)
        if i is None:                    # nothing clears the tolerance
            i = int(np.argmin(errs))
        sel = ((method == m) & (nb == combos[i][1])
               & (kd == combos[i][2]) & (kc == combos[i][3]))
        sample = err[sel][np.isfinite(err[sel])]
        p5, p95 = (np.percentile(sample, [5, 95]) if sample.size
                   else (np.nan, np.nan))

        # gain against the affine-split solver from the PAIRED measurement
        # (baseline and prediction on the same theta, microseconds apart, so the
        # clock drift divides out). The other two gains have no paired partner
        # and stay ratios of medians, quoted to the nearest integer.
        if "t_dbmm_paired" in d:
            paired = np.asarray(d["t_dbmm_paired"], dtype=float)[sel] * 1e3
            on = t_on[sel]
            good = np.isfinite(paired) & np.isfinite(on) & (on > 0)
            gain_V = (float(np.median(paired[good] / on[good])) if good.any()
                      else solver["t_V"] / costs[i])
        else:
            gain_V = solver["t_V"] / costs[i]

        out.append(dict(method=m, tag=tag, label=labels[i], cost=costs[i],
                        err=errs[i], p5=float(p5), p95=float(p95),
                        gain_rmat=solver["t_rmat"] / costs[i],
                        gain_full=solver["t_full"] / costs[i],
                        gain_V=gain_V))
    return solver, out


def table_cost(systems=SUITE):
    """One forward evaluation, three baselines, and what the emulator costs.

    Every number here comes from `operating_rows`, which is also what the
    inline macros are built from.
    """
    rows, n_valid_seen = [], 0
    for key in systems:
        system = SYSTEMS[key]
        solver, configs = operating_rows(key)
        n_valid_seen = max(n_valid_seen, solver.get("n_valid", 0))
        first = True
        for c in configs:
            head = (rf"{system.label} & {c['tag']} & ${solver['n_train']}$ & "
                    rf"{_num(solver['t_rmat'], 1)} "
                    rf"& {_num(solver['t_full'], 1)} & {_num(solver['t_V'], 2)}"
                    if first else rf" & {c['tag']} & & & &")
            rows.append(
                rf"{head} & {c['label']} & {_num(c['cost'], 2)} & "
                rf"{_gain(c['gain_rmat'])} & "
                rf"{_gain(c['gain_full'])} & "
                rf"{_gain(c['gain_V'])} & "
                rf"{_sci(c['err'])} & {_sci(c['p5'])}--{_sci(c['p95'])} \\")
            first = False
        rows.append(r"\addlinespace[2pt]")
    if rows and rows[-1].startswith(r"\addlinespace"):
        rows.pop()

    caption = (
        r"The cost of one forward evaluation, and what it amortises to. "
        r"Medians over the timed draws, each the minimum of at least seven "
        r"repetitions, on one core. The two error columns are the metric of "
        r"Table~\ref{tab:metrics} on the elements of $\mathbf{U}$: the worst "
        r"off-diagonal element that exists where the system is coupled, the "
        r"elastic element where it is not. They are read off "
        rf"${n_valid_seen}$ validation draws, none of them seen in training; the "
        r"p95 in particular needs a sample of that size to be an estimate rather "
        r"than close to the largest value observed. Absolute times reproduce to between $5$ and "
        r"$30$ per cent between runs, so the gain against the $V$-only baseline "
        r"is \emph{paired}, baseline and prediction timed on the same $\theta$ "
        r"microseconds apart; the other two are unpaired and rounded. It is a median of per-draw ratios, so it does not equal the ratio of the two median columns. "
        r"\textbf{The R-matrix column is an upper bound, not the cost of the "
        r"method}: that implementation rebuilds a $\theta$-independent kinetic "
        r"matrix on every call and inverts where $N_c$ right-hand sides would "
        r"do. The gain against $V$ only is the "
        r"one to defend. Each configuration is the cheapest the autocalibration "
        r"proposes that clears the posterior tolerance. "
        r"Two things this table is not. The offline cost is paid \emph{per "
        r"energy node and per $J^\pi$ block}: a campaign over twenty energies "
        r"pays it twenty times, so the training minutes quoted here are not the "
        r"training cost of a full campaign. And every time in it is Python "
        r"against Python. It is the ratio that carries over to another "
        r"implementation, not the absolute values: a compiled solver would move "
        r"both the baseline and the emulator columns.")
    return _tabular(
        [r"& & & \multicolumn{3}{c}{solver, ms per evaluation}"
         r"  & \multicolumn{2}{c}{emulator}"
         r"  & \multicolumn{3}{c}{gain against}"
         r"  & \multicolumn{2}{c}{error} \\",
         r"\cmidrule(lr){4-6}\cmidrule(lr){7-8}\cmidrule(lr){9-11}"
         r"\cmidrule(lr){12-13}",
         r"System & method & $n_{\rm train}$ & R-matrix & rebuild & split"
         r"  & operating config. & ms & R-matrix & rebuild & split"
         r"  & median & p5--p95 \\"],
        rows, "llrrrrrrrrrrr", caption, "tab:cost", "cat",
        note="R-matrix column is an upper bound, not the method's cost",
        compact=True)


def table_interior(systems=SUITE):
    """psi(r) and delta(E) against the solver, medians over validation draws.

    Both numbers come from the views the two appendix figures are drawn from,
    so the table and the figures cannot disagree.
    """
    rows = []
    n_resid = None
    for key in systems:
        system = SYSTEMS[key]
        psi = views.wavefunction_vs_emulators(key)["residual"].notes
        delta = views.phase_shift_vs_emulators(key)["residual"].notes
        _, meta = cache.read(key, "interior")
        n_resid = meta.get("n_resid", n_resid)
        rows.append(
            rf"{system.label} & {_sci(psi.get('median_rbm', np.nan))} & "
            rf"{_sci(psi.get('median_lrom', np.nan))} & "
            rf"{_num(delta.get('median_rbm', np.nan), 4)} & "
            rf"{_num(delta.get('median_lrom', np.nan), 4)} \\")

    caption = (
        rf"The interior solution and the phase shift against the solver, median "
        rf"over ${n_resid}$ validation draws outside every training set. The "
        rf"deviation on $\psi$ is pointwise, as a fraction of the peak "
        rf"amplitude; that on $\delta$ is absolute, since a phase shift passing "
        rf"through zero makes a relative error unbounded.")
    return _tabular(
        [r"& \multicolumn{2}{c}{$\psi(r)$, fraction of peak} "
         r"& \multicolumn{2}{c}{$\delta(E)$, degrees}\\",
         r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
         r"System & RBM & LROM & RBM & LROM \\"],
        rows, "lrrrr", caption, "tab:interior", "interior")


#: Appended to table_budget's suite. alpha+d is the case the argument predicts
#: to be neutral (its coupling parameter also sits on the diagonal): the row
#: that does not move is what makes the others a measurement.
BUDGET_CONTROL = "alpha_d"

#: n+58Ni: a one-phonon vibrational coupling on a 0+ ground state has no
#: reorientation because <0|Y_lambda|0> vanishes, so the deformation is absent
#: from the diagonal whatever the model does -- unlike alpha+24Mg and n+238U,
#: where the reorientation is switched off by a modelling choice.
BUDGET_PHYSICAL = "n58Ni"


def table_budget(systems=SUITE):
    """Joint against split predictor budget, at fixed total K.

    Only coupled systems appear. The joint and split errors on each observable
    are divided, not both printed; a ratio below FLAT reads as no gain (timing
    and draw scatter at that size).
    """
    FLAT = 1.5
    rows, n_valid = [], None
    for extra in (BUDGET_PHYSICAL, BUDGET_CONTROL):
        if extra not in systems:
            systems = tuple(systems) + (extra,)
    for key in systems:
        system = SYSTEMS[key]
        try:
            d, meta = cache.read(key, "budget")
        except Exception:
            continue                            # skipped by the run, not missing
        n_valid = meta.get("n_valid", n_valid)
        med = lambda k: float(np.nanmedian(np.asarray(d[k], dtype=float)))  # noqa: E731

        def gain(joint, split):
            j, s = med(joint), med(split)
            return j / s if np.isfinite(j) and np.isfinite(s) and s > 0 else np.nan

        g_el, g_in = gain("err_el_joint", "err_el_split"), gain("err_in_joint", "err_in_split")
        travel = float(meta["diag_moves"])

        def cell(g):
            """The ratio joint/split. A ratio at or below 1/FLAT is a loss and
            is coloured as one; between the two bands is a dash."""
            if not np.isfinite(g):
                return "--"
            if g >= FLAT:
                return rf"$\times{g:.0f}$"
            if g <= 1.0 / FLAT:
                return rf"\textcolor{{Vloss}}{{$\divisionsymbol{1.0 / g:.1f}$}}"
            return "--"

        # how far the diagonal travels when the coupling parameter crosses its
        # box, relative to its own size; exactly zero is forbidden by a
        # selection rule.
        t = "$0$" if travel == 0.0 else rf"${travel:.1g}$".replace("e-0", r"\times10^{-") \
            .replace("$1\\times10^{", "$10^{")
        if "10^{" in t and not t.endswith("}$"):
            t = t[:-1] + "}$"

        applied = ("split" if meta.get("split_applied", True) else "joint")
        rows.append(
            rf"{system.label} & {meta.get('coup_label', '')} & "
            rf"${meta['K_diag']}{{+}}{meta['K_coup']}$ & "
            rf"{t} & {cell(g_el)} & {cell(g_in)} & \emph{{{applied}}} \\")

    caption = (
        rf"Joint against split predictor budget, at fixed total $K$: \emph{{split}} "
        rf"divides $K$ as shown, \emph{{joint}} spends it all on the diagonal, and "
        rf"everything else is held equal over ${n_valid}$ validation draws. "
        rf"Column~4 is how far the diagonal potential travels, relative to its own "
        rf"size, when the coupling parameter of column~2 crosses its box; it is the "
        rf"quantity the rule of Section~\ref{{subsec:budget}} is read on. "
        rf"Columns~5 and~6 are the median error of the joint budget divided by that "
        rf"of the split one, on the elastic and on the inelastic element: "
        rf"$\times n$ means the split is $n$ times better, $\divisionsymbol n$ that it is $n$ "
        rf"times worse, and a dash that the two lie within a factor of ${FLAT}$. "
        rf"The last column is the allocation the autocalibration applies, which "
        rf"follows the rule rather than a choice: split where the diagonal does not "
        rf"move, joint everywhere else. $n+{{}}^{{58}}$Ni is the only system whose "
        rf"coupling parameter is absent from the diagonal exactly, by the selection "
        rf"rule of Section~\ref{{subsec:cc}}.")

    return _tabular(
        [r"& & & & \multicolumn{2}{c}{gain from splitting} & \\",
         r"\cmidrule(lr){5-6}",
         r"System & param. & $K_{\rm diag}{+}K_{\rm coup}$ "
         r"& diagonal travel & elastic & inelastic & applied \\"],
        rows, "llrlrrl", caption, "tab:budget", "budget")


# --- the inline numbers ----------------------------------------------

_TEX_DIGITS = str.maketrans("0123456789", "ZOTHFVSEIN")

#: Systems the amplitude argument names, in sentence order. Not SUITE: n+58Ni is
#: the one system whose coupling parameter is absent from the diagonal.
AMPLITUDE_SYSTEMS = ("alpha12C_band", "n58Ni", "n238U", "alpha24Mg")


def _amplitude_ratio(key, n_r=200):
    """How much further the diagonal block travels over the box than the coupling.

    Each parameter is pushed to the top of its box in turn; the largest absolute
    change of any diagonal potential over the mesh is taken, and the same for
    the coupling block. Absolute, not relative: what decides where a maxvol pass
    puts its points is the size of the signature entries, not their size
    relative to their own block. Reads the preset, not the cache.
    """
    system = SYSTEMS[key]
    channels, model, theta_c, bounds = system.preset_fn()
    r = np.linspace(1e-3, system.R, n_r)
    V_diag_c, V_coup_c = model(theta_c)
    base_diag = [np.asarray(V_diag_c(r, c), dtype=complex) for c in channels]
    base_coup = np.asarray(V_coup_c(r, channels[0], channels[1]), dtype=complex)

    d_max = c_max = 0.0
    for j in range(len(theta_c)):
        theta = theta_c.copy()
        theta[j] = bounds[j, 1]
        Vd, Vc = model(theta)
        d_max = max(d_max, max(
            np.max(np.abs(np.asarray(Vd(r, c), dtype=complex) - b))
            for c, b in zip(channels, base_diag)))
        c_max = max(c_max, np.max(np.abs(
            np.asarray(Vc(r, channels[0], channels[1]), dtype=complex)
            - base_coup)))
    return float(d_max / max(c_max, 1e-30))


def _macro_name(tag, system_key):
    r"""A TeX control sequence name: letters only, digits spelled out
    (\NstarRbmNFZCa, not \NstarRbmN40Ca -- TeX allows no digits in control
    sequences)."""
    raw = tag + "".join(w.capitalize() for w in
                        system_key.replace("+", "_").split("_"))
    return "".join(c for c in raw if c.isalnum()).translate(_TEX_DIGITS)


#: Bands the summary table reads its verdict symbols off. Presentation only:
#: "clears" is the same EPS_POST metrics.operating_point applies; the middle
#: band keeps a configuration on the threshold from printing as a plain failure.
VERDICT_MARGIN = 1.5      # within this factor of the tolerance: on the threshold
GAIN_REAL = 1.5           # at or above: a gain worth having
GAIN_NONE = 1.05          # below: the reduction returns nothing


def _verdict_error(x, tol=None):
    """Y, A or N for an error against the posterior tolerance."""
    from .style import EPS_POST
    tol = EPS_POST if tol is None else tol
    if not np.isfinite(x):
        return "N"
    if x <= tol:
        return "Y"
    return "A" if x <= VERDICT_MARGIN * tol else "N"


def _verdict_gain(g):
    """Y, A or N for an online gain against the affine-split solver."""
    if not np.isfinite(g):
        return "N"
    if g >= GAIN_REAL:
        return "Y"
    return "A" if g >= GAIN_NONE else "N"


def _log(x):
    r"""log10(x), for a TikZ coordinate on a logarithmic axis (a $6.8\times
    10^{-3}$ macro is unusable as a coordinate). Non-finite emits a dash, so a
    figure built on one fails to compile rather than drawing a stray point.
    """
    return f"{np.log10(x):.2f}" if np.isfinite(x) and x > 0 else "--"


def _sigfig(x, n=2):
    """x rounded to n significant figures, rendered without a decimal point."""
    if not np.isfinite(x) or x == 0:
        return "0"
    mag = int(np.floor(np.log10(abs(x))))
    step = 10.0 ** (mag - n + 1)
    return f"{round(round(x / step) * step):d}"


def macros(systems=SUITE):
    r"""The numbers the prose quotes, as \newcommand definitions, so a paragraph
    regenerates with the figure it describes."""
    lines = [_header("cat + amortisation + manifold")]
    # the amplitude ratios behind the by-block budget split: four numbers in one
    # sentence, the shape that rots when typed.
    for key in AMPLITUDE_SYSTEMS:
        lines.append(rf"\newcommand{{\{_macro_name('AmpRatio', key)}}}"
                     rf"{{{_sigfig(_amplitude_ratio(key), 2)}}}")
    for key in systems:
        amort = views.amortisation(key)["breakeven"].notes
        _, cat_meta = cache.read(key, "cat")
        _, man_meta = cache.read(key, "manifold")
        for note, tag in (("cross_rbm", "NstarRbm"), ("cross_lrom", "NstarLrom")):
            v = amort.get(note, np.nan)
            lines.append(
                rf"\newcommand{{\{_macro_name(tag, key)}}}"
                rf"{{{'--' if not np.isfinite(v) else f'{v:.0f}'}}}")
        # break-even as a multiple of the training set: an emulator repays its
        # own snapshots.
        n_tr = cat_meta.get("n_train")
        ratio_star = (amort.get("cross_rbm", np.nan) / float(n_tr)
                      if n_tr else np.nan)
        lines.append(rf"\newcommand{{\{_macro_name('RatioStar', key)}}}"
                     rf"{{{'--' if not np.isfinite(ratio_star) else f'{ratio_star:.2f}'}}}")
        # from the blocks: a macro is quoted next to a figure and must describe
        # the same run.
        lines.append(rf"\newcommand{{\{_macro_name('Ntrain', key)}}}"
                     rf"{{{cat_meta.get('n_train', '')}}}")
        lines.append(rf"\newcommand{{\{_macro_name('Nb', key)}}}"
                     rf"{{{man_meta.get('nb', '')}}}")

        # paired win fraction, as an integer percentage: the trials are
        # correlated within a draw.
        notes = views.error_distribution(key)["distribution"].notes
        for note, tag in (("win_rbm", "WinRbm"),):
            v = notes.get(note, np.nan)
            lines.append(rf"\newcommand{{\{_macro_name(tag, key)}}}"
                         rf"{{{'--' if not np.isfinite(v) else f'{100 * v:.0f}'}}}")
        for note, tag in (("n_energy_rbm", "NEnRbm"), ("n_energy", "NEn"),
                          ("n_trial", "NTrial")):
            lines.append(rf"\newcommand{{\{_macro_name(tag, key)}}}"
                         rf"{{{notes.get(note, '--')}}}")

        # mesh-scan endpoints, for the LROM asymptotic-claim sentence. A missing
        # scaling block costs only these two numbers.
        try:
            mesh = views.online_vs_mesh(key)["ratio"].notes
        except Exception:
            mesh = {}
        for note, tag in (("ratio_lo", "MeshLo"), ("ratio_hi", "MeshHi")):
            v = mesh.get(note, np.nan)
            lines.append(rf"\newcommand{{\{_macro_name(tag, key)}}}"
                         rf"{{{'--' if not np.isfinite(v) else f'{v:.2f}'}}}")

        # operating point of each method, same selection table_cost prints (both
        # call operating_rows).
        solver, configs = operating_rows(key)
        # what the affine split alone is worth before any reduction.
        lines.append(rf"\newcommand{{\{_macro_name('GainSplit', key)}}}"
                     rf"{{{solver['t_full'] / solver['t_V']:.1f}}}")
        for c in configs:
            t = c["tag"].title()          # Rbm, Lrom
            for tag, val in ((f"GainV{t}", f"{c['gain_V']:.1f}"),
                             (f"Ton{t}", f"{c['cost']:.2f}"),
                             (f"LMed{t}", _log(c["err"])),
                             (f"LPtail{t}", _log(c["p95"])),
                             (f"OkMed{t}", _verdict_error(c["err"])),
                             (f"OkTail{t}", _verdict_error(c["p95"])),
                             (f"OkGain{t}", _verdict_gain(c["gain_V"]))):
                lines.append(rf"\newcommand{{\{_macro_name(tag, key)}}}{{{val}}}")

    # campaign numbers: a crossing of two straight lines whose slopes are
    # measured, so it regenerates with them.
    from .api import campaign
    camp = campaign(1e5, systems=systems)
    for key in systems:
        rows = camp.loc[key]
        cross = rows["N_cross"].iloc[0] if "N_cross" in rows else np.nan
        # two significant figures: the crossing is where two timing lines meet
        # and the timings reproduce only to tens of per cent.
        lines.append(rf"\newcommand{{\{_macro_name('Ncross', key)}}}"
                     rf"{{{'--' if not np.isfinite(cross) else _sigfig(cross, 2)}}}")
        lines.append(rf"\newcommand{{\{_macro_name('Cheaper', key)}}}"
                     rf"{{{rows['cheaper_at_N'].iloc[0]}}}")
        for m in ("RBM", "LROM"):
            if m in rows.index:
                lines.append(rf"\newcommand{{\{_macro_name('Tcamp' + m.title(), key)}}}"
                             rf"{{{rows.loc[m, 'T_min']:.1f}}}")
        lines.append(rf"\newcommand{{\{_macro_name('TcampSolver', key)}}}"
                     rf"{{{rows['solver_T_min'].iloc[0]:.0f}}}")
    return "\n".join(lines) + "\n"


# --- writing them ---------------------------------------------------

BUILDERS = {"t_manifold": table_manifold, "t_cost": table_cost,
            "t_interior": table_interior, "t_budget": table_budget,
            "t_macros": macros}


def write_all(systems=SUITE, only=None):
    """Write every table; report what was written and what could not be.

    A builder that raises does not abort the rest -- its failure is returned as
    a row.
    """
    target = out_dir()
    target.mkdir(parents=True, exist_ok=True)
    rows = []
    for name, build in BUILDERS.items():
        if only and name not in only:
            continue
        path = target / f"{name}.tex"
        try:
            text = build(systems)
        except Exception as exc:
            rows.append(dict(table=name, state=f"{type(exc).__name__}: {exc}"[:70],
                             path="", bytes=0))
            continue
        path.write_text(text, encoding="utf-8")
        rows.append(dict(table=name, state="written", path=str(path),
                         bytes=len(text.encode("utf-8"))))
    return pd.DataFrame(rows).set_index("table")
